language: python
python:
  - "3.6"
# command to install dependencies

before_install:
  - sudo apt-get update

  # use raxml-ng from bioconda - there are compilation errors...
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install --force-reinstall numpy==1.14.5
  - conda install -c bioconda raxml-ng

#    # install gappa (for EPA)
#  - mkdir gappa
#  - cd gappa
#  - wget https://github.com/lczech/gappa/archive/master.zip
#  - unzip master.zip
#  - cd gappa-master
#  - make
#  - cd ..
#  - cd ..

    # install modeltest-ng
  - mkdir modeltest-ng
  - cd modeltest-ng
  - wget https://github.com/ddarriba/modeltest/files/3790686/modeltest-ng-0.1.6.tar.gz
  - tar -xvf modeltest-ng-0.1.6.tar.gz
  - cd modeltest-ng-0.1.6/
  - sudo apt-get install qt5-default
  - ./build.sh
  - cd ..
  - cd ..
  - pwd

install:
  # install requirements of physcraper
  - pip install --quiet -r requirements.txt
  - pip install --quiet .

# command to run tests
script:
  - wget 'https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz'
  - gunzip  -cd taxdump.tar.gz | (tar xvf - names.dmp nodes.dmp)
  - mkdir taxonomy
  - mv *.dmp taxonomy/
  - pytest tests/test_*

after_success:
  - curl -s https://codecov.io/bash | bash
